development:
  adapter: mysql2
  database: arpabet_development
  username: root
  encoding: utf8
  password: 4Bcd3fg

test:
  adapter: mysql2
  database: arpabet_test
  username: root
  encoding: utf8
  password: 4Bcd3fg
  
production:
  adapter: mysql2
  database: arpabet_development
  username: root
  encoding: utf8